[platformio]
default_envs = rainpoint_bridge

[env:rainpoint_bridge]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DRAINPOINT_RADIO_COUNT=1
  -DRAINPOINT_RESEARCH_BENCH=0
  -DRAINPOINT_SENSOR_A_CANDIDATE=0
  -DRAINPOINT_PAIRING_GENERALIZATION=1
  -DRAINPOINT_ROUTINE_ACK_CANDIDATE=1
  -DRAINPOINT_OTA_CANDIDATE=1
  -DRAINPOINT_VALVE_PAIRING_CANDIDATE=1
  -DRAINPOINT_FIRMWARE_VERSION=\"0.12.5\"
  -DRAINPOINT_STATUS_LED_PIN=2
  -DRAINPOINT_CONFIRM_BUTTON_PIN=0
