[platformio]
default_envs = esp32dev_single

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -std=gnu++17
  -DRAINPOINT_RADIO_COUNT=1
  -DRAINPOINT_RESEARCH_BENCH=0
  -DRAINPOINT_FIRMWARE_VERSION=\"0.6.0\"
  -DRAINPOINT_STATUS_LED_PIN=2
  -DRAINPOINT_CONFIRM_BUTTON_PIN=0
build_unflags =
  -std=gnu++11

[env:esp32dev_single]
build_flags = ${env.build_flags}

[env:esp32dev_dual]
build_unflags =
  ${env.build_unflags}
  -DRAINPOINT_RADIO_COUNT=1
build_flags =
  ${env.build_flags}
  -DRAINPOINT_RADIO_COUNT=2

[env:esp32dev_single_bench]
build_unflags =
  ${env.build_unflags}
  -DRAINPOINT_RESEARCH_BENCH=0
build_flags =
  ${env.build_flags}
  -DRAINPOINT_RESEARCH_BENCH=1
